### ISSUE TITLE
Chrome 技巧_「 中文 issues 」

### ISSUE THREAD

**Issue by dendoink** [dendoink/FrontendWingman#1]
For Chinese developers to discuss.
提供给中文开发者讨论问题

**Comment by kergee** [comment]
你好，https://www.frontendwingman.com/Chrome/C06/workspaceTips.html 标题Chrome误写成了Chorme

**Comment by dendoink** [comment]
> 你好，https://www.frontendwingman.com/Chrome/C06/workspaceTips.html 标题Chrome误写成了Chorme

tks！已收到，我尽快修复

**Comment by dendoink** [comment]
> 你好，https://www.frontendwingman.com/Chrome/C06/workspaceTips.html 标题Chrome误写成了Chorme

已修复，非常感谢。
